### ISSUE TITLE
Drag and Drop of gadgets onto a dashboard widget

### ISSUE THREAD

**Issue by robertmazzo** [DataTorrent/malhar-angular-dashboard#104]
Hello,
I am integrating your dashboard widgets framework into my application, and creating a drag and drop feature which will trigger a new dashboard widget. This will replace the bootstrap dropdown menu which allows a user to add a new widget.

It's this section here which I'd like to remove :
        <div class="btn-group" ng-if="options.widgetButtons">
            <button ng-repeat="widget in widgetDefs"
                    ng-click="addWidgetInternal($event, widget);" type="button" class="btn btn-primary">
                {{widget.name}}
            </button>
        </div>
and move the call to addWidgetInternal() into my controller code (specifically in my drop event) like this :

     (function () {
    'use strict';
    angular.module('rage')
        .controller('MainCtrl',
            ['$scope', '$interval', '$window', 'widgetDefinitions',
            'defaultWidgets', 'gadgetInitService', initOptions]);

    function initOptions($scope, widgetDefinitions, defaultWidgets, gadgetInitService) {
         $scope.dashboardOptions = {
            widgetButtons: false,   // 'false' makes it a dropdown of options
            widgetDefinitions: widgetDefinitions,   // see factory.js
            defaultWidgets: defaultWidgets,
            storage: $window.localStorage,
            storageId: 'rage.ui',
            hideWidgetSettings: false
        };

        // DRAG AND DROP EVENTS         
        $scope.handleDrop = function () {
            //alert('Dropped !');
            $scope.addWidgetInternal();
        }        
    }
})();

My problem is that I can't figure out how to call $scope.addWidgetInternal() from a controller. Is this possible ?

thank you in advance,
Bob

**Comment by robertmazzo** [comment]
I figured it out folks. I ended up creating an ondrop event on the dashboard directive :

     link: function (scope, element) {

              // handle drop event from the gadgets drag-drop operation (see gadgets-include.html)
              var el = element[0];
              el.ondrop = function (e) {
                  e.dataTransfer.dropEffect = 'move';
                  var item = document.getElementById(e.dataTransfer.getData('text'));                 
                  //this.appendChild(item.cloneNode(true));  // image gets dropped on div     
                  var newWidget = _.findWhere(scope.widgetDefs, { name: item.id });
                  // This will add the new widget div to the dashboard                  
                  scope.addWidgetInternal(e, newWidget);
              };

and my main view contains both droppable and dashboard directives, but on two different divs :+1: 
      <div class="col-lg-12" data-droppable drop="handleDrop">
            <div id="dash" dashboard="dashboardOptions" class="dashboard-container"></div>
        </div>

**Comment by andyperlitch** [comment]
Very cool! Perhaps we could make this an opt-in feature.

**Comment by JloraMedsis** [comment]
@robertmazzo Hey man i having the same issue, but i went further i changed the whole drag and drop system of the dashboard and that didnt work out, then i saw this thread, can u elaborate on how you configured the widget definitions container (the replace of the dropdown), cause i kind of did it with ui-sortable, but i cant drag my widgets any where i want,
i apprecite you could help me with this

**Comment by wvary** [comment]
@JloraMedsis If you can create a test page for us to review and debug, we'd be happy to assist with this.

**Comment by JloraMedsis** [comment]
hi @wvary, im gonna setup a test enviroment for you to look at it, give me 30 mins to spin up a VM and install everything... how can i let you know im ready ?

**Comment by wvary** [comment]
@JloraMedsis, please update this issue with the url and I'll take a look.

**Comment by JloraMedsis** [comment]
@wvary Hey this is the test page is was telling you about, http://35.185.9.107/#/.... click the upper right corner icon to bring the widgets and the drag a widget from there to the dashboard, but try to add it somewhere between first and second widget, it will add it but at the end.. ill be here if u dont understand what in trying to explain

**Comment by wvary** [comment]
@JloraMedsis I'm looking at the code right now, but it would be helpful if you don't use minified js files.

**Comment by JloraMedsis** [comment]
@wvary files are not minified now, please check it out now, and thanks!

**Comment by robertmazzo** [comment]
@JloraMedsis - I could grab the code at home and get you more details, but in the meantime see my post above where I mentioned that I figured it out.
I actually added a link: function to the original Malhar dashboard directive.

and my main view decorated with both droppable and dashboard directives, 
    <div class="col-lg-12" data-droppable drop="handleDrop">
          <div id="dash" dashboard="dashboardOptions" class="dashboard-container"></div>
     </div>

But I didn't change the whole ui-sortable thing. I just wanted to drag an image from the left nav menu in my application, and drop it onto the main dashboard. That's where the `el.drop` event above made it happen.

Keep in touch.
Bob

**Comment by JloraMedsis** [comment]
I rolledback my drag changes and used ui-sortable again, i used everything
You said but the el.drop its doesnt get triggered... If You can check the
URL i provided with the example and wacth the code and perhaps tell me what
am i missing


Thanks for all

**Comment by wvary** [comment]
@JloraMedsis Menu is not working anymore.

**Comment by JloraMedsis** [comment]
Menu is working ok, that implementation is configured with sessionStorage
maybe clean it ir something, maybe tell me what is not working

Thanks in advance

**Comment by wvary** [comment]
@JloraMedsis working now, maybe it was in the middle of a release.  I also tried in incognito mode.

**Comment by JloraMedsis** [comment]
Glad to hear that

**Comment by JloraMedsis** [comment]
@wvary Did you find anything?

**Comment by JloraMedsis** [comment]
Well guys i kinda of found a solution to my problem, i reordered the widget array and thats all....
