### ISSUE TITLE
Adding multiple widget to widgetdefinition in forloop

### ISSUE THREAD

**Issue by mahitaande** [DataTorrent/malhar-angular-dashboard#105]
Hi,
   I am using malhar-angular-dashboard for showing my widgets. I have my widgets list in a data base as the number of widgets for a dashboard is variable and the user can add custom widgets. I would like to add the widget definitions by making an http request to get the list and loop through it to add the properties.
I came up with the following code for that

    $scope.widgetDefinitions = [];
    $http.get(baseUrl + 'Dashboard/GetWidgets').success(function (data) {
        var widgets = data;
        for (var i = 0; i < widgets.length; i++) {
            $scope.widgetDefinitions.push(
                {
                    name: widgets[i].Name,
                    dataAttrName: 'data',
                    title: widgets[i].Title,
                    style: {
                        width: widgets[i].Width
                    },
                    dataModelOptions: function (result, widget) {
                        if (widget.dataModel && widget.dataModel.updateLimit) {
                            widget.dataModel.updateLimit(result.dataModelOptions.limit);
                        }
                    },
                    dataModelType: DxPWidgetDataModel
                }
            );
        }        
    });

When I debug I see that the http request is made to the server and the widgets list is returned. however in the end $scope.widgetDefinitions is always an empty object. 
Please advise how this can be achieved. 

Thank you,
Mahita

**Comment by andyperlitch** [comment]
Currently, widgetDefinitions cannot be defined post-instantiation of the dashboard. But that doesn't mean this is possible. You could do what you have there, and then instantiate the dashboard once all widgets have loaded. This would take just a bit of fancy footwork in the markup, perhaps something like this:

```HTML
<div ng-if="widgetDefinitions.length"><!-- use ngIf not ngShow, this way the inner directive will not be instantiated -->
  <div dashboard="dashboardOptions"></div>
</div>
```

**Comment by mahitaande** [comment]
Thank you for the suggestion. I tweaked my mark up to include the widgetDefinitions count but that did not work either.

Here is my markup 


<div id="dashboardContent" class="fullHeightWidth dashboardMainCntnr">
    <div data-ng-controller="DashboardCtrl" class="dashboardController fullHeightWidth">
        <div ng-if="widgetDefinitions.length" class="dasboardInnerCntnr fullHeight">
            <div id="dashboardId" class="sqDashboard fullHeightWidth" dashboard="dashboardOptions">
            </div>
        </div>
    </div>
</div>

And my dashboard controller definition is
angular.module('Dashboard', ['app.service', 'ngGrid', 'ui.sortable', 'ui.dashboard', 'ui.bootstrap'
]).controller('DashboardCtrl', function ($scope, $http, $window, DxPWidgetDataModel, $modal) {

    $scope.widgetDefinitions = [];
    $http.get(baseUrl + 'Dashboard/GetWidgets').success(function (data) {
        var widgets = data;
        for (var i = 0; i < widgets.length; i++) {
            $scope.widgetDefinitions.push(
                {
                    name: widgets[i].Name,
                    dataAttrName: 'data',
                    title: widgets[i].Title,
                    style: {
                        width: widgets[i].Width
                    },
                    dataModelOptions: function (result, widget) {
                        if (widget.dataModel && widget.dataModel.updateLimit) {
                            widget.dataModel.updateLimit(result.dataModelOptions.limit);
                        }
                    },
                    dataModelType: DxPWidgetDataModel
                }
            );
        }        
    });

    $scope.defaultWidgets = _.map($scope.widgetDefinitions, function (widgetDef) {
        return {
            name: widgetDef.name
        };
    });

    /**
     *Purpose: To set the general setting for dashborad
     */
    $scope.dashboardOptions = {
        widgetButtons: false,
        hideWidgetName: true,
        hideToolbar: true,
        hideWidgetClose: true,
        hideWidgetSettings: true,
        widgetDefinitions: $scope.widgetDefinitions,
        defaultWidgets: $scope.defaultWidgets
    };
});

When I debug, I see that the widgetDefinition.length is set to 2 which is current. However no widgets are displayed. If I replace the http request to hardcode the widgetDefinitions value to a specific entry it works just fine. 

I do not see any errors either. 

Please advise if I am missing anything.

Thank you,
Mahita

**Comment by andyperlitch** [comment]
I think i see what is wrong: you are setting $scope.defaultWidgets from an empty widgetDefinitions array. Solution: put the statement:

```JavaScript
    $scope.defaultWidgets = _.map($scope.widgetDefinitions, function (widgetDef) {
        return {
            name: widgetDef.name
        };
    });
```

at the end of the success callback from your ajax call

**Comment by robertmazzo** [comment]
Hello,
I'm also using the Malhar dashboard in my web application.

Forgive me if I'm missing something here, but I was thinking of a simple solution as it relates to the widgetDefinitions factory. If you're not going the factory route, then perhaps this won't work.

Anyway, Instead of returning a hard-coded list in the factory, as in the demo example :

     (function () {
    'use strict';
    angular.module('rage')
        .factory('widgetDefinitions', ['RandomDataModel',  widgetDefinitions])

    function widgetDefinitions(RandomDataModel, ) {
        var size = {width: '30%',height: '60px'};
        return [                            
           {    
               name: 'datamodel',
               directive: 'wt-scope-watch',
               dataAttrName: 'value',
               dataModelType: RandomDataModel    
           },
          {
              name: 'resizable',
              templateUrl: 'app/shared/template2/resizable.html',
              attrs: {
                  class: 'demo-widget-resizable'
              }
          }
        ];
    }            
    })();

Perhaps you could inject a widget definitions data service into this factory, as such:

(function () {
    'use strict';
    angular.module('rage')
        .factory('widgetDefinitions', ['widgetDefDataService', widgetDefinitions])

    function widgetDefinitions(myDataService) {
       var widgetDefinitions = [];
       myDataService.getWidgetDefs.success(function (data) {
           var widgets = data;
           for (var i = 0; i < widgets.length; i++) {
                     $scope.widgetDefinitions.push( ... );
           }
      }
        return widgetDefinitions ;
    }            
})();

I hope this helps.

best regards,
Bob

**Comment by mahitaande** [comment]
Thank you for your suggestions.
Both of the solutions you suggested worked.
