### ISSUE TITLE
how to add some default content to widget content div

### ISSUE THREAD

**Issue by robertmazzo** [DataTorrent/malhar-angular-dashboard#106]
I'd like to add some default content in the main widget content div supplied in dashboard.html.
However, it appears that the templateUrl of the widgetDefinitions factory will always override that content.

In the dashboard.html template, let's say for example I add a span tag:

               <div class="panel-body widget-content" ng-style="widget.contentStyle">
                   <span>HELLO THERE</span>
                </div>
then in the widgetDefinitions factory I hook into the resizable widget for testing:

     function widgetDefinitions(RandomDataModel, ColumnChartDataModel, TreeGridDataModel) {
        return [    
        {
              name: 'resizable',
              templateUrl: 'app/shared/template2/resizable.html',
              attrs: {  class: 'demo-widget-resizable'  }
          }
       ];
     }

My  `<span>HELLO THERE</span>` content is removed, so I would like to figure out a way to simply have each widget created initially with this default HELLO THERE content (in reality I will be adding an image, and having that image file change dynamically acc. to my widget defs).

I know that I can add the default content in my example to `resizable.html`, but in my case I will end of having 15 or 20 different html files representing different widget types. I don't want to copy my default content into each html template.

thanks in advance.

Bob

**Comment by andyperlitch** [comment]
Hmmm not sure if you'll be able to get around adding that content to all the different html files... perhaps you could improve it a little bit by having a simple ngInclude element with an ngIf directive in each template, eg:

```HTML
<div ng-include="'my/default-content.html" ng-if="someLoadingFlag"></div>
```

Sorry, can't think of a better solution. I'll put it in the back of my mind and might think of something better. The problem is that the dashboard doesnt (and shouldnt) know about the loading/loaded state of your custom widgets.

**Comment by robertmazzo** [comment]
You're right Andy. The dashboard shouldn't know about the content of the custom widgets.
However, for my business case, the user will be :
1) Dragging an image (from an image list) onto the main Dashboard.
2) Once the new widget gets rendered then they are presented with an image, and an option to "Configure the gadget".

This "Confgure Gadget" icon will be the initial default for EACH widget.

So I was actually thinking the same thing as you before. Have some sort of ng-if or something.

Thanks for the response. I'll keep ya posted.

**Comment by robertmazzo** [comment]
The other possibility would be to modify the compileTemplate function within the DashboardWidgetCtrl . In this case I could set a flag on the widget and then compile whatever template string I want.
ex/
     var templateString = $scope.makeTemplateString();
     var defaultTemplateString = $scope.makeDefaultTemplateString();

**Comment by robertmazzo** [comment]
with much consideration, and a bit of trial-and-error, the most straight-forward solution is a combination of mine and Andy's ideas. 
That is, I will not touch the "widget-content" div, nor the $scope.makeTemplateString() function.
For now, I have a created an additional `<div>` to cover my default content. Then I will use the `ng-if` to determine which `<div>` I want to show in the widget.
Here's a sample of what's already running :

       <div ui-sortable="sortableOptions" ng-model="widgets" class="dashboard-widget-area">
        <div ng-repeat="widget in widgets" ng-style="widget.containerStyle" class="widget-container" widget>
            <div class="widget panel panel-default">
                <div class="widget-header panel-heading">
                    <h3 class="panel-title">
                        <span class="widget-title" ng-dblclick="editTitle(widget)" ng-hide="widget.editingTitle">{{widget.title}}</span>
                        <form action="" class="widget-title" ng-show="widget.editingTitle" ng-submit="saveTitleEdit(widget)">
                            <input type="text" ng-model="widget.title" class="form-control">
                        </form>
                        <span class="label label-primary" ng-if="!options.hideWidgetName">{{widget.name}}</span>
                        <span ng-click="removeWidget(widget);" class="glyphicon glyphicon-remove" ng-if="!options.hideWidgetClose"></span>
                        <span ng-click="openWidgetSettings(widget);" class="glyphicon glyphicon-cog" ng-if="!options.hideWidgetSettings"></span>
                    </h3>
                </div>               

                
                <div id="defContent" ng-if="!widget.gadgetConfigured" class="imageHolder" ng-click="openWidgetSettings(widget);">                    
                        <img ng-src="Images/{{widget.initImage}}" width="80" height="95"  />
                        <br /><a href="">Click to configure</a>                        
                </div>   
                   
                <div ng-if="widget.gadgetConfigured" class="panel-body widget-content" ng-style="widget.contentStyle"></div>
                <div class="widget-ew-resizer" ng-mousedown="grabResizer($event)"></div>
                <div ng-if="widget.enableVerticalResize" class="widget-s-resizer" ng-mousedown="grabSouthResizer($event)"></div>
            </div>
        </div>
    </div>

**Comment by andyperlitch** [comment]
Glad you could find a solution that works for you. If you think of a solution that is better but requires some changes to the library, I'd be more than happy to consider a pull request.

Best of luck!

**Comment by robertmazzo** [comment]
Thanks Andy. I think there are more pressing requests, as mine is very specific to my business case.
I believe the multiple layout scenario is a much higher need. And I see that there are some demos for that, so I'll dig in deeper...
best regards.
