### ISSUE TITLE
Resize width and height

### ISSUE THREAD

**Issue by mahitaande** [DataTorrent/malhar-angular-dashboard#108]
Hi,
    In my application, the dashboard occupies only half of the screen , the other half is another partial view. I added widgets to my dashboard and everything is fine. However widget resizing does not seem to have any boundaries. I can just keep dragging my mouse the widget expands beyond bounds. Could you please advise if there is a way I can set the max width and height I can resize my widget to? Also, I want my widget to adjust the height according to the widget content. I tried setting height propertu to "" and "auto". In both the cases, I saw vertical scrollbars. Please advise how this can be avoided.

Thank you,
Mahita

**Comment by wvary** [comment]
Hi @mahitaande,

Take a look at the current open PR https://github.com/DataTorrent/malhar-angular-dashboard/pull/182. It has min/max width support, as well as an example show the widget height adjusted automatically as the table grows or shrinks.  Click on the dynamic data menu for this.

As for the min/max height, we don't have this feature yet, but you can pretty much implement it using the min/max width as a reference.  Feel free to create a PR and we'll review and merge it.

Regards,

Willet
