### ISSUE TITLE
Multiple data models for widget

### ISSUE THREAD

**Issue by tarlepp** [DataTorrent/malhar-angular-dashboard#109]
Hi, I'm wondering if there is a way to bind multiple dataAttr with each having different data model. Is this possible or is there another way to update multiple directive scope values from custom data model?

**Comment by wvary** [comment]
Hi @tarlepp,

We do have examples with different widgets pointing to different data sources and types/models.

Also, look at this PR https://github.com/DataTorrent/malhar-angular-dashboard/pull/182 to examples of update different widgets as the data models are updated.

Regards,

Willet

**Comment by tarlepp** [comment]
Quite long time for reply... Seems like there is something fixed (maybe) but cannot be sure. We solved this issue within our own custom code, because wasn't getting any feedback...

Another thing is that it has been almost two years - so not so quick reply...

**Comment by wvary** [comment]
Hi @tarlepp,

I apologize for the long delay in responding.
We are going through all the open issues to make sure we address all inquiries, feature requests and bugs.

Regards,

Willet
