### ISSUE TITLE
Width resize not working unless width specified - containerStyle width = NaNNaN

### ISSUE THREAD

**Issue by PhilBroadbent** [DataTorrent/malhar-angular-dashboard#110]
Hi, having a problem with the resize of width of the demo widgets.

Unless I specify width attribute for the defaultWidgets or widgetDefinitions, the containerStyle width isn't always set to 33%. This results in the widthUnits not being set, so resizing results in values of NaN...etc.

I can't figure out why containerStyle width is not always set properly. Please advise.

**Comment by andyperlitch** [comment]
Sorry, this was a bug in the code. I have fixed it.

Regards,
Andy

**Comment by spiermar** [comment]
Is this in 0.8.2? I just updated from 0.4 and resizing is not working at all. No error messages or anything. Just drag the borders and nothing happens. Setting size with
size: {
    width: '25%',
    height: '250px'
}
Is also not working. The old style: ... is working fine though. I'm probably missing something. Any specific changes to allow resizing if migrating from an older version?

**Comment by spiermar** [comment]
Ignore it. Found the problem:

<div ng-repeat="widget in widgets" ng-style="widget.style" class="widget-container" widget>

changed to:

<div ng-repeat="widget in widgets" ng-style="widget.containerStyle" class="widget-container" widget>

On the template.
