### ISSUE TITLE
Custom widget header actions

### ISSUE THREAD

**Issue by tarlepp** [DataTorrent/malhar-angular-dashboard#111]
Hi, I need to add some widget specified custom actions to widget header and those actions should actually use widget directive function.

Any pointers to implement this?

**Comment by robertmazzo** [comment]
You might need to be more specific; however in the meantime, couldn't you just place your directive within the main dashboard.html view ?
I mean in this section here : 
         <div class="widget-header panel-heading">
               <div myDirectiveName="myOptions"></div>
                 ....
         </div>  
Where 'myDirectiveName' is your new directive name.

The other option is to go in and modify the 'dashboard' directive code directly and add the functionality you need.

I, for example, needed an ondrop event so I ammended the link function in the original dashboard directive code: 

       el.ondrop = function (e) {
          ...
        }



good luck,
Bob

**Comment by andyperlitch** [comment]
@robertmazzo is correct in this approach. @tarlepp I recommend using a [custom template](https://github.com/DataTorrent/malhar-angular-dashboard#custom-template) that has your custom widget header logic there.

**Comment by andyperlitch** [comment]
closing... please reopen if you have more questions
