### ISSUE TITLE
Error handling on data models

### ISSUE THREAD

**Issue by tarlepp** [DataTorrent/malhar-angular-dashboard#115]
I didn't find any examples of error handling on data models. Basically when ever some error happens in data model I would like to notice actual widget about that. eg. show some specified error on widget when error occurs.

Any pointers for this?

**Comment by robertmazzo** [comment]
Hi,
This might be related to something I was also trying to do; that is, to add some special widget content under special circumstances. The idea is that I would have the ability to show/hide that div content on the fly. See :

      https://github.com/DataTorrent/malhar-angular-dashboard/issues/112  

In the meantime, I would just add a <div> within the main dashboard.html template - but then you would need a way to show/hide that div when needed (i.e. Angular's ng-if or ng-show).

ex/        <div class="panel-body widget-content" ng-style="widget.contentStyle"></div> 
             <div class="myErrorContent"> {{myError}} </div>

I hope this helps a bit...
Bob

**Comment by wvary** [comment]
Hi @tarlepp,

I'm not sure which data models you're referring to.
Assuming you are polling using an API, then that service should handle any network/server errors and update the data models according.  Then the binding between the data model and the html should do it's magic to notify you of errors.
If you have some code whether in a branch or plunker/jsfiddle, I'd be happy to review it with you.

Regards,

Willet

**Comment by tarlepp** [comment]
@wvary the problem was if I fetch some data to widget via promise how to handle possible errors that happens on that call. There wasn't real handling for those, so we built one of our own - not a hard job, but this kind of stuff should be implemented and documented on this repo.

Another thing is that it has been almost two years - so not so quick reply...

**Comment by wvary** [comment]
@tarlepp I apologize for responding for late.  I'm going through all the open issues (a few every month).  At the current rate, we should either respond or resolve all open issues in a couple of months.

I'm glad to hear you found a solution for your situation.  This is an open source project, so feel free to contribute if you feel someone else will benefit from this feature.

Regards,

Willet
