### ISSUE TITLE
Control ID generation of layouts in dashboard-layouts

### ISSUE THREAD

**Issue by tarlepp** [DataTorrent/malhar-angular-dashboard#118]
Hi,

I just implemented custom dataStorage to store layouts and states to database and noticed some not expected behaviour.

I'm using database ID as in layout.id, and this is problem because `layoutStorage.add(newLayout);` generates own id for new layout, and actual save won't change that according to dataStorage setItem() response.

I did a hack for this, but I'm not satisfied with my implementation about this. Any pointers how this should be done?

**Comment by andyperlitch** [comment]
Currently the dashboard ids are auto-generated, and it will take a little refactoring to change this behavior, but I don't see it being that much of a change. I don't have bandwidth to tackle this right now, but I will tag this as a new feature and rename it to better convey the request. If you can put together a pull request, I would be more than happy to merge it, barring any changes I may suggest!

**Comment by tarlepp** [comment]
Basically the problem lies there https://github.com/DataTorrent/malhar-angular-dashboard/blob/master/dist/angular-ui-dashboard.js#L339-L346

1) new layout is added to scope _before_ it's actually saved
2) actual dashboard layout save triggeres two times (scope.makeLayoutActive() and layoutStorage.save())

I'm not sure about that "little" refactoring on this one, but hopefully I'm wrong :D

**Comment by wvary** [comment]
Hi @tarlepp,

Looking at the current code, it is possible to set the DashboardState id and LayoutStorage id when you instantiate them.  If you still have an issue with implementing your own storage and setting IDs, provide us with some code and we'll be happy to review it.

Regards,

Willet

**Comment by wvary** [comment]
No response from OP so closing issue.

**Comment by tarlepp** [comment]
yep, we solved this one with custom stuff... and  really we didn't have the time to make that thing os at that time - which is shame :(

but if i remember correct i have somewhere really refactored version on this library, adds these multiuser things and stuff. I'll try to look that out this weekend - I hope that I find that one :D

**Comment by tarlepp** [comment]
and basically responses after a year of some issue - you're really, really late...
