### ISSUE TITLE
Saving chart/grid gadget options and setting to localStorage

### ISSUE THREAD

**Issue by robertmazzo** [DataTorrent/malhar-angular-dashboard#124]
Hi Andy,
Forgive me ahead of time if I'm missing something here regarding the saving of layouts, but I was trying to figure out why all the data options and settings on my UI gadgets are NOT persisting to localStorage.

In other words, I have a Kendo UI chart gadget that gets renders in a Dashboard widget.

Here are the steps I take to render a chart gadget in a dashboard widget:
1) I drag an icon onto the dashboard (I added some code in your directive to handle a drop event).
2) I click on the settings icon to launch the modal "configuration" window
3)  I configure my chart gadget and submit the request to my server.
4) I parse the server data, then bind the JSON results to $scope.result.dataModel (i.e. I've added additional objects such as 'chartOptions.dataSource' and 'chartOptions.series' onto the dataModel in order to make this work).
 
Problem: When I "hard" refresh my page (or re-run the app), I was hoping that the localStorage objects would have contained ALL my chart data - and therefore render the chart as before.

Question: What do I need to do in order to save ALL my dashboard widget data so that my chart gadget gets re-rendered (until the next time I reconfigure the chart with newly-fetched server data).

Am I looking at modify the save: and load: functions of the 'DashboardState' factory ? 

Or do I perhaps need to load up the persisted data in my customized 'ColumnChartDataModel' factory ?

**Comment by andyperlitch** [comment]
Hey Robert,

I may have some insight as to why this is happening, but first, do me a favor: try using the code on the branch `release-2.0.0`; I think this may be fixed.

-Andy

**Comment by robertmazzo** [comment]
I'm still getting comfortable with github. Where exactly would I download the update ? Is there a zip file somewhere in https://github.com/DataTorrent/malhar-angular-dashboard ?
thank you very much...
Bob

**Comment by andyperlitch** [comment]
Hey bob,

I actually JUST now drafted the 1.0.0 tag/release on github. You can just do bower install malhar-angular-dashboard#v1.0.0, and then update the references to the distribution files (they have been changed in v1.0.0 to reflect the repository name, e.g. `dist/malhar-angular-dashboard.css` and `dist/malhar-angular-dashboard.js`.

Let me know if you have trouble.

**Comment by robertmazzo** [comment]
I noticed a "Download Zip " option at https://github.com/DataTorrent/malhar-angular-dashboard, off to the right. Would that work ?

**Comment by andyperlitch** [comment]
Yea that'll work.

**Comment by robertmazzo** [comment]
thanks. I'm also looking at the more complex demo of UI Gadgets here http://datatorrent.github.io/malhar-dashboard-webapp/#/ .
Perhaps that would give me some ideas re: how you're saving/retrieving the gadget data...although it might be a bit out of date....not sure...

**Comment by robertmazzo** [comment]
Hi,
when reviewing the source, I'm seeing dashboard.js in two places:
1)  dist/malhar-angular-dashboard.js
2)  src/components/directives/dashboard/dashboard.js
After downloading the zip file, I noticed the dashboard directive code is slightly different between 1) and 2).
Please advise.
thank you ,
Bob

**Comment by andyperlitch** [comment]
Bob,

Thanks for pointing this out, it was in fact an error that the two were incorrect. I have since updated master and created a new version (1.0.1) with the fix. Please re-download and it should be good.

Thanks,
Andy

**Comment by robertmazzo** [comment]
Great, thanks Andy.

**Comment by zunairzubair** [comment]
Hey @robertmazzo,
I know its quite a long time since you posted this question. But I am implementing a same kind of implementation. I would love to know how you managed to save the dashboard state and how you loaded the dashboard state back on page load from server.
Thanks :)

**Comment by robertmazzo** [comment]
I'll pull some code for you today.

Bob

**Comment by robertmazzo** [comment]
Here's my heavily modified 'DashboardState' factory. 
I had to add a `_getItemFromAPI` anonymous function.
Also, the `load` and `save` functions have my comments with 'Bob' preceded by a date.

Initially I was storing to localStorage object, then reading from that. But eventually we wrote an API layer to save/load to/from the backend.

I hope this helps...

`angular.module('ui.dashboard')
.factory('DashboardState', ['$log', '$q', 'dashboardcontext', '$rootScope', function ($log, $q, dashboardcontext, $rootScope) {

  var that = this;

  function DashboardState(storage, id, hash, widgetDefinitions, stringify) {
	  this.storage = storage;
	  this.id = id;
	  this.hash = hash;
	  this.widgetDefinitions = widgetDefinitions;
	  this.stringify = stringify;
  }

  DashboardState.prototype = {
	  /**
	   * Takes array of widget instance objects, serializes, 
	   * and saves state.
	   * 
	   * @param  {Array} widgets  scope.widgets from dashboard directive
	   * @return {Boolean}        true on success, false on failure
	   */
	  save: function (widgets) {

		  if (!this.storage) {
			  return true;
		  }

		  var serialized = _.map(widgets, function (widget) {
			  var widgetObject = {
				  id: widget.id,
				  title: widget.title,
				  name: widget.name,
				  style: widget.style,
				  size: widget.size,
				  dataModelOptions: widget.dataModelOptions,
				  storageHash: widget.storageHash,
				  attrs: widget.attrs,
				  initImage: widget.initImage,
				  gadgetConfigured: widget.gadgetConfigured,
				  loaded: widget.loaded
			  };

			  return widgetObject;
		  });

		  var item = { widgets: serialized, hash: this.hash };

		  if (this.stringify) {
			  item = JSON.stringify(item);
		  }              

		  //this.storage.setItem(this.id, item);    // comment original Malhar line. modify below - 05/04/2015 Bob:

		  // to support a unique Dashboard Layout Id; assigned in onTreeSelect() of navigation-controller.js - // 05/04/2015 Bob:
		  var thisLayoutId = $rootScope.rageSessionVars.currDashboardSelected;
		  if (thisLayoutId != null && thisLayoutId != undefined) {
			  this.storage.setItem(thisLayoutId, item);
		  }
		  else {
			  this.storage.setItem(this.id, item);
		  }

		  // SERVER-SIDE API CALL TO PERSIST DASHBOARD TO STORAGE - 09/03/2015 Bob:
		  var sid = $rootScope.rageSessionVars.sessionID;
		  var userid = $rootScope.rageSessionVars.userID;
		  var dashboardId = thisLayoutId;     // this.id;

		  dashboardcontext.setDashboardImage(sid, userid, dashboardId, item).then(function (data) {
			  if (data.status == "FAIL") {
				  window.alert("Failed to update dashboard. " + data.messages);
			  }
			  else {
				  var results = data;
			  }
		  });

		  return true;
	  },	  
	 load: function (dashboardId) {        // sent in from navigation-controller call - 05/01/2015 Bob:
		  
		  var useLocalStorage = false;     // retrieve from localStorage or via API layer - 09/04/2015 Bob:

		  var serialized;

		  if (useLocalStorage) {           // retrieve dashboard layout from localStorage
			  if (!this.storage) {
				  return null;
			  }
			  if (dashboardId != null && dashboardId != undefined) {
				  serialized = this.storage.getItem(dashboardId);

				  // save the current dashboard id for next load
				  this.storage.setItem("defaultDashboardId", dashboardId);
			  }
		  }
		  else {
			  //serialized = this.storage.getItem(this.id);

			  // FETCH DASHBOARD HERE !! FYI: dashboardId stored in treeview menu of navigation-controller - 05/04/2015 Bob:
			  if (dashboardId != null && dashboardId != undefined) {

				  this.storage.setItem("defaultDashboardId", dashboardId);  // fetch this in this.initUserSession on user-service
				  if ($rootScope.rageSessionVars.currDashboardName != undefined) {
					  this.storage.setItem("defaultDashboardName", $rootScope.rageSessionVars.currDashboardName);
				  }
				  
				  that = this;
				  return this._getItemFromAPI($rootScope).then(function (data) {                           
					  // save current current dashboard id for next time - 06/11/2015 Bob:      
		  
					  return that._handleSyncLoad(data, true);

				   });                      
			  }
			  else {
				  // revert to original line; see dashboardOptions to main-controller
				  serialized = this.storage.getItem(this.id);
			  }                  
		  }

		  if (serialized) {
			  // check for promise
			  if (angular.isObject(serialized)) {    // && angular.isFunction(serialized.then)) {    // modifed line 09/04/2015 Bob:
				  return this._handleAsyncLoad(serialized);
			  }
			  // otherwise handle synchronous load
			  return this._handleSyncLoad(serialized);
		  } else {
			  return null;
		  }

	  },         

	  _getItemFromAPI: function ($rootscope) {
		  // SERVER-SIDE API CALL TO PERSIST DASHBOARD TO STORAGE - 09/03/2015 Bob:
		  var sid = $rootScope.rageSessionVars.sessionID;
		  var userid = $rootScope.rageSessionVars.userID;
		  var dashboardId = $rootScope.rageSessionVars.currDashboardSelected; // assigned in 'NavBarCtrl'

		  return dashboardcontext.getDashboardImage(sid, userid, dashboardId).then(function (data) {
			  if (data.status == "FAIL") {
				  window.alert("Failed to retrieve dashboard. " + data.messages);
				  return false;
			  }
			  else {                      
				  return data.data[0];
			  }
		  }, function (error) {
			  console.log("Failed to retrieve dashboard in _getItemFromAPI. ");
		  });            
	  },

	  _handleSyncLoad: function (serialized, isParsed) {
		  // @serialized {JSON} - parsed or unparsed Json object 
		  // @isParsed {Boolean} - false if loaded from localStorage.getItem(); true if loaded from API, Json string already parsed.

		  var deserialized, result = [];

		  if (!serialized) {
			  return null;
		  }

		  if (isParsed) {    // JSON already deserialzed in load: above; see _getItemFromAPI().then data object - 09/04/2015 Bob:

			deserialized = serialized;               

		  }
		  else {
			  if (this.stringify) {
				  try { // to deserialize the string

					  deserialized = JSON.parse(serialized);

				  } catch (e) {

					  // bad JSON, log a warning and return
					  $log.warn('Serialized dashboard state was malformed and could not be parsed: ', serialized);
					  return null;

				  }
			  }
			  else {
				  deserialized = serialized;
			  }
		  }

		  // check hash against current hash
		  if (deserialized.hash !== this.hash) {

			  $log.info('Serialized dashboard from storage was stale (old hash: ' + deserialized.hash + ', new hash: ' + this.hash + ')');
			  this.storage.removeItem(this.id);
			  return null;

		  }

		  // Cache widgets
		  var savedWidgetDefs = deserialized.widgets;

		  // instantiate widgets from stored data
		  for (var i = 0; i < savedWidgetDefs.length; i++) {

			  // deserialized object
			  var savedWidgetDef = savedWidgetDefs[i];

			  // widget definition to use
			  var widgetDefinition = this.widgetDefinitions.getByName(savedWidgetDef.name);

			  // check for no widget
			  if (!widgetDefinition) {
				  // no widget definition found, remove and return false
				  $log.warn('Widget with name "' + savedWidgetDef.name + '" was not found in given widget definition objects');
				  continue;
			  }

			  // check widget-specific storageHash
			  if (widgetDefinition.hasOwnProperty('storageHash') && widgetDefinition.storageHash !== savedWidgetDef.storageHash) {
				  // widget definition was found, but storageHash was stale, removing storage
				  $log.info('Widget Definition Object with name "' + savedWidgetDef.name + '" was found ' +
					'but the storageHash property on the widget definition is different from that on the ' +
					'serialized widget loaded from storage. hash from storage: "' + savedWidgetDef.storageHash + '"' +
					', hash from WDO: "' + widgetDefinition.storageHash + '"');
				  continue;
			  }
			  savedWidgetDef.loaded = true;     // 10/30/2015 Bob:
			  // push instantiated widget to result array
			  result.push(savedWidgetDef);
		  }

		  return result;
	  },

	  _handleAsyncLoad: function (promise) {
		  var self = this;
		  var deferred = $q.defer();
		  promise.then(
			// success
			function (res) {
				var result = self._handleSyncLoad(res);
				if (result) {
					deferred.resolve(result);
				} else {
					deferred.reject(result);
				}
			},
			// failure
			function (res) {
				deferred.reject(res);
			}
		  );

		  return deferred.promise;
	  }

  };
  
  return DashboardState;
}])`
