### ISSUE TITLE
How to resize widget from modal controller code

### ISSUE THREAD

**Issue by robertmazzo** [DataTorrent/malhar-angular-dashboard#125]
Hi Andy,
I understand how to set the widget size property via 'widgetDefinitions' factory, for example:
``` 
            {
                name: 'chart_treelist',
                title: 'Report Grid',
                size: {width: '30%',height: '60px'},
                templateUrl: 'app/shared/gadget-templates/tree-list.html',
                dataAttrName: 'treeListOptions',
                dataModelType: TreeListDataModel,
                gadgetType: 'grid',
                settingsModalOptions: {   // for grid gadget config window
                    templateUrl: 'app/shared/include/grid-config/widget-config-grid.html',
                    controller: 'GridSettingsCtrl as settings',
                  }
             }
```
However, once I launch the modal, I want to widen the widget size for my Kendo chart to render properly (otherwise it looks too small if widget width is too small).

So I change the widget in my controller before closing the modal :
```
           $scope.result.size.width = "70%";

           $modalInstance.close($scope.result);
```

Then back in the dashboard directive code, the modal close event is handled here:
```
                 // Set resolve and reject callbacks for the result promise
                  modalInstance.result.then(
                    function (result) {
                        // Call the close callback
                        onClose(result, widget, scope);                     
                        scope.$broadcast('widgetSettingsClosed', widget, result);                        
                        scope.$emit('widgetChanged', widget);
                    }
 ```    
Even though I can inspect the widget.size.width value, it doesn't actually widen the widget. 

Am I using the right approach ?

thanks for your troubles again,

Bob

**Comment by robertmazzo** [comment]
Andy,
Seems like I figured it out, but only in the directive itself; specifically in the modalInstance.result.then section:

       modalInstance.result.then(
                    function (result) {
                        // Call the close callback
                        onClose(result, widget, scope);

                        if (widget.gadgetType == 'chart') {
                            // we want to force the Kendo chart to render bigger.
                            widget.setWidth(60);         // WORKING !!!!!!!
                            widget.setHeight(300);
                        }

                        scope.$broadcast('widgetSettingsClosed', widget, result);                                             
                        scope.$emit('widgetChanged', widget);
                    },

**Comment by andyperlitch** [comment]
hmmmm try setting the $scope.result.containerStyle.width. Also, the `widget` object on the scope has a `setWidth` method that you should be able to utilize. Take a look at the [WidgetModel.js file](https://github.com/DataTorrent/malhar-angular-dashboard/blob/master/src/components/models/WidgetModel.js).

**Comment by robertmazzo** [comment]
This appears to work best for me. That is, resizing after I close the modal instance:

      modalInstance.result.then(
                    function (result) {

                        // Call the close callback
                        onClose(result, widget, scope);
                       // added new widget property - BM:
                        widget.setHeight(widget.fixedSize.height);
                        widget.setWidth(widget.fixedSize.width);

                        scope.$broadcast('widgetSettingsClosed', widget, result);
                         scope.$emit('widgetChanged', widget);
                    },
