### ISSUE TITLE
Dynamic system to load widgets

### ISSUE THREAD

**Issue by pihomeserver** [DataTorrent/malhar-angular-dashboard#128]
Hello,
I would like to load all available widgets with a dynamic way. My users should be able to install different widgets from a store-like page so i don't know yet all future widgets. It's like a wordpress plugin system.

Do you have any idea how to perform that ? I try to use ocLazyLoad but the controller linked to the widget is not loaded properly.

Thank you

**Comment by robertmazzo** [comment]
Hello,
Maybe you can provide more details for a better community response.
However, if I understand correctly you want a user to select a widget from a predetermined list, and then create it on the dashboard.
Firstly, look up the 'widgetDefinitions' factory code. This is where all the widget definitions are defined.
Second, look up the 'dashboard' directive code. There is a link section there which can be used to handle DOM events.
For example, if you're using drag/drop you can do something like:

      link: function (scope, element) {
              var el = element[0];
              el.ondrop = function (e) {
              var newWidget = _.findWhere(scope.widgetDefs, { name: item.id }); // GET WIDGET ID
              scope.addWidgetInternal(e, newWidget); // ADD WIDGET TO DASHBOARD
      }
If you need to add a widget from a controller somewhere, I found out about a little hack you can add in some controller:

       angular.element(document.getElementById('dashboard')).scope().addWidgetInternal();

anyhow, I hope you can find some tips from here...


good luck,
Bob

**Comment by andyperlitch** [comment]
@pihomeserver your project requirements should be possible with the dashboard. In fact, this is similar to one use-case we are implementing using this, but much of the heavy-lifting occurs outside the dashboard, specifically the ad-hoc loading of modules after angular has initialized. I actually have a little prototype repo that illustrates one way to accomplish this here: https://github.com/andyperlitch/angular-adhoc-module-loading-example.

The bigger challenge might be adding to the widgetDefinitions collection after the dashboard has initialized. This illustrates a potential need to expose methods that allow manipulation of the WidgetDefCollection underneath.

**Comment by pihomeserver** [comment]
Thanks guys for your help ! I will have a look and test that way. I need to master angular principles first, for now i just play with it ...

**Comment by wvary** [comment]
@pihomeserver Let us know if you still need help with this question. For now, I'm going to close this issue...Thanks.
