### ISSUE TITLE
element parameter is undefined on openWidgetSettings() method

### ISSUE THREAD

**Issue by robertmazzo** [DataTorrent/malhar-angular-dashboard#129]
Hello,
Here's a little tricky one I'm having trouble with regarding the onClose() event of the modal.
I'd like to get access to the DOM element when I close the modal in this section of the `dashboard` directive, but the `element` parameter is undefined:

         scope.openWidgetSettings = function (widget, element) {
               ....
              modalInstance.result.then(
                    function (result) {

                        // Call the close callback
                        onClose(result, widget, scope);
                       scope.$broadcast('widgetSettingsClosed', widget, result);

                       // 'element' variable UNDEFINED here !!!
                       var chart = element.find('.k-chart').data("kendoChart");
                        if (chart != undefined) {                        
                            chart.resize($(".k-chart"));
                        }

                       scope.$emit('widgetChanged', widget);
                    },
                 ....
                );
              };

I can do something similar in the `$scope.grabResizer()` method because I have access to the `$element` object; however, this is not the case in `modalInstance.result.then`.

Can I get some advice on how to get the kendo object from the container when I close the modal via `element.find('.k-chart').data("kendoChart");` ?

I've even tried to add a second parameter on the `dashboard.html` template :
           
     <span title="config" ng-click="openWidgetSettings(widget, e);" class="glyphicon glyphicon-cog" ng-if="!options.hideWidgetSettings"></span>

But I'm not sure how to handle that either...

thanks,
Bob

**Comment by robertmazzo** [comment]
hi,
Is anyone else jumping to answer questions around here ?  I know I try to when I see a new post.
thanks,
Bob

**Comment by andyperlitch** [comment]
Hey @robertmazzo,

I try to answer questions as timely as possible, but my work on this project is really limited by my day job (and my free time), so I apologize for the silence at times. I really appreciate you fielding some of the questions!

As far as your question, you could potentially solve this issue by overriding the [default controller](https://github.com/DataTorrent/malhar-angular-dashboard/blob/master/src/components/directives/dashboard/WidgetSettingsCtrl.js) on the `settingsModalOptions` object. Basically change the `ok` method as it is defined there with something like:

```
angular.module('ui.dashboard')
  .controller('WidgetSettingsCtrl', ['$scope', '$modalInstance', 'widget', '$element', function ($scope, $modalInstance, widget, $element) {
    // add widget to scope
    $scope.widget = widget;

    // set up result object
    $scope.result = jQuery.extend(true, {}, widget);

    $scope.ok = function () {
      // DO SOMETHING HERE WITH KENDO ELEMENT USING $element
      $modalInstance.close($scope.result);
    };

    $scope.cancel = function () {
      $modalInstance.dismiss('cancel');
    };
  }]);
```

**Comment by robertmazzo** [comment]
thanks Andy. I appreciate your time, and I know its limited. I also don't mind fielding questions, as I love the framework - and working on understanding it well.

I'll try out what you're saying here...

regards,
Bob

**Comment by robertmazzo** [comment]
Andy,
I can't seem to inject $element service in the default controller as in your example above. I've tried this elsewhere, and I always get the angular injection error. It doesn't recognize it.
I'd like to have access to the DOM element when I close the settings modal, but I can't figure that out.
thx
Bob

**Comment by robertmazzo** [comment]
Andy,
I've also tried to use jQuery selector to get access to the parent of `.modal-body`. I can do that, but unfortunately the Kendo `resize()` method still has no affect. It does work, by the way, when triggered from a click event coming directly from the widget (i.e. a refresh icon, or a maximize icon).

     var el = $('.modal-body');
     var chartElem = el.parent().parent().parent().parent().find('.k-chart').data("kendoChart");
     if (chartElem != undefined) {
               chartElem.setOptions({ chartArea: { width: chartElem.getSize().width * .95, height: chartElem.getSize().height * .90 } });                            
                chartElem.resize($(".k-chart"));
      }
