### ISSUE TITLE
Trying to understand widget vs. scope object in dashboard directive

### ISSUE THREAD

**Issue by robertmazzo** [DataTorrent/malhar-angular-dashboard#131]
Hello Andy et al.,
I'm working around an issue in the `directive` code where I'm trying to re-assign the `widget` object, and replace the entire object with the contents of the `result` object.

I do see the use of jQuery.extend() method, used to merge the properties here :

     onSettingsClose: function (result, widget) { 
                      jQuery.extend(true, widget, result);    
             }

 however that's NOT what I'm looking for. That is actually merging the `result` object with `widget`, and therefore retaining some old data on `widget` itself. I need to outright REPLACE the `widget` object.

I think it comes from my confusion regarding `this.dataModelOptions` vs. `this.dataModelType.dataModelOptions` .

In other words, I'm updating `this.dateModelOptions` in my custom factory's updateScope:

      updateScope: function (data) {                          
              this.dataModelOptions = data;
          },

However when I get into debugging the dashboard directive code in the ` modalInstance.result.then` section of `scope.openWidgetSettings`, I'm seeing my object settings in two places :

     `this.dataModelOptions` 

and 

`this.dataModelType.dataModelOptions` 

Perhaps you can shed some light on why I'm seeing it in two places. I'm really studying the code base to try and get a handle on it.

In the meantime, I've added `widget.dataModelOptions = result.dataModelOptions;` - and it seems to be working; although I'm concerned whether I'm using the framework properly and efficiently :

      modalInstance.result.then(
               function (result) {

                     // Call the close callback
                     onClose(result, widget, scope);

                     // added because jQuery.extend() onSettingsClose: above doesn't take care of this - BM:
                     widget.dataModelOptions = result.dataModelOptions;
                
                     scope.$broadcast('widgetSettingsClosed', widget, result);
                                           
                        //AW Persist title change from options editor         
                        scope.$emit('widgetChanged', widget);
                    },
thanks,

Bob

**Comment by andyperlitch** [comment]
Hey Bob,

`widget.dataModelOptions` and `widget.dataModel.dataModelOptions` should actually reference the same object. Your solution seems to look fine to me, although why don't you just put `widget.dataModelOptions = result.dataModelOptions;` into `onSettingsClose` on your dashboard options? When you specify this function on options, it will override the default behavior using `jQuery.extend(true, widget, result);`. For example, this would be your options:

```js
{
  // other options
  onSettingsClose: function(result, widget) { // NOTE: dashboard scope is also passed as 3rd argument
    widget.dataModelOptions = result.dataModelOptions;
  },
  // other options
}
```

I don't see a reason you would need to modify the library code. Let me know if that helps.

**Comment by robertmazzo** [comment]
okay thank you Andy. 
First: I was hoping you would say that about dataModelOptions referencing the same object. In some strange cases, however, I think I might have screwed something up. I saw two different property values between `widget.dataModelOptions` and `widget.dataModel.dataModelOptions` . 

I'll try the `onSettingsClose` idea you gave me. I see now that I can add that to `$scope.dashboardOptions` in my `mainCtrl` code. 

Thanks for your response.

Bob
