### ISSUE TITLE
"Sub" tabs

### ISSUE THREAD

**Issue by mattlucas121** [DataTorrent/malhar-angular-dashboard#132]
Hi,

I'm currently using the dashboard framework and it works great! I wanted to know if anyone could tell me if there is any concept of "sub" tabs. Basically what I'm trying to achieve is another layer of nested tabs under the layouts. On the top level you'd have layout 1, 2, 3 and then under layout 1 you'd have another set of tabs called a, b, and c, under layout 2 you'd see d, e, f and 3 would contain g, h, i.

Does anyone have any thoughts on this?

Thanks!
Matt

**Comment by robertmazzo** [comment]
I really have no idea if this would work, but in looking the the layouts demo the first thing that came to mind was embedding this `ng-repeat` within the `template\dashboard.html` file:

      <div ng-repeat="layout in layouts | filter:isActive" dashboard="layout.dashboard" template-url="template/dashboard.html"></div>

Perhaps Andy would have more insight on that.

As per my requirements, I need to wire up a unique dashboard per menu item. i.e. user chooses from a tree menu on the left nav bar of my website, then a full dashboard gets rendered. This looks challenging, but possible.

**Comment by mattlucas121** [comment]
Closing this as the dashboard layout tabs ended up being sufficient. Thanks!
