### ISSUE TITLE
how to initialize $scope.dashboardOptions via REST service

### ISSUE THREAD

**Issue by gisslemi** [DataTorrent/malhar-angular-dashboard#133]
Hello everyone. :)

I currently try to initialize the $scope.dashboardOptions via a REST service.
The problem ist not to handle the ajax request. I receive the correct JSON data from the server.
But when I try to initialize the $scope.dashboardOptions in the 'DemoCtrl' controller I get an error 'Cannot read property 'settingsModalOptions' of undefined'. This error comes from 'malhar-angular-dashboard.js:37'

I assume, this is because of the async  call of $resource.
When I debug the application and set breakpoints, I can see that the $scope.dashboardOptions are set AFTER  'scope.options.settingsModalOptions = scope.options.settingsModalOptions || {};' in malhar-angular-dashboard.js.

How can I avoid this error and where do I have to implement the AJAX request?

Many thanks and sorry for asking that noob question! :)

Code snippet from 'DemoCtrl':

        var dashboardId = 5;

        $resource("/api/dashboardoptions/:id")
            .get({ id: dashboardId })
        .$promise.then(
        function (response, $scope) {
            $scope.dashboardOptions = response.dashboardOptions;
            $scope.dashboardOptions['defaultWidgets'] = response.dashboardOptions.defaultWidgets;
            $scope.dashboardOptions['storageId'] = response.dashboardOptions.storageId;
            $scope.dashboardOptions['widgetButtons'] = response.dashboardOptions.widgetButtons;
            $scope.dashboardOptions['widgetDefinitions'] = response.dashboardOptions.widgetDefinitions;
            $scope.dashboardOptions['storage'] = $window.localStorage;
        });

**Comment by gisslemi** [comment]
After doing some research I came up with the following solution:
- remove the ng-app directive
- bootstrap the app explicitly via angular.bootstrap(document, ["app"]);
- get REST data from server
- on success, call angular.bootstrap.
- done. :)

code:
```
(function () {
    'use strict';
    var app = angular
        .module('app', ['ngRoute', 'ui.dashboard', 'btford.markdown', 'ngResource', 'ui.dashboard', 'ui.widgets', 'ui.models'])
        .config(function ($routeProvider) {
           }      

        .controller('DemoCtrl', function ($scope, $interval, $window, config) {      
        })

    fetchData().then(bootstrapApplication);

    function fetchData() {

        var initInjector = angular.injector(["ng"]);
        var $http = initInjector.get("$http");

        return $http.get("/api/dashboardoptions/5").then(function (response) {
            app.value("config", response.data);
        }, function (errorResponse) {
            // Handle error case
        });
    }

    function bootstrapApplication() {

        angular.element(document).ready(function () {
            angular.bootstrap(document, ["app"]);
        });
    }
}());

```
This solution was found here: https://blog.mariusschulz.com/2014/10/22/asynchronously-bootstrapping-angularjs-applications-with-server-side-data

**Comment by andyperlitch** [comment]
Sorry for the late response. There is actually an easier solution. All you have to do is add an ng-if statement to your template with your dashboard element, like so:
```HTML
<div ng-if="dashboardOptions">
  <dashboard options="dashboardOptions"></dashboard>
</div>
```

The ng-if directive works here because it won't actually initialize the inner dashboard until options are available.

**Comment by gisslemi** [comment]
Thanks for your response and your suggestion. Your solution is really elegant. Much better then my attempts. :)
