### ISSUE TITLE
Link to Simple Demo in Readme is broken

### ISSUE THREAD

**Issue by stvogel** [DataTorrent/malhar-angular-dashboard#139]
This is a fantastic dashboard. I just started playing around with it a bit, but am already impressed.
I'd like to have a look at the source code of the "simple demo" but the link in the readme just points to a 404.
Where can I have a look at the demo-code?

Thanks a lot
Stefan

**Comment by stvogel** [comment]
Ok, just to answer my own question.
Simply had to run:
```gulp serve```
and the demo opens on http://localhost:3000
Sometimes it's so easy :-)

**Comment by andyperlitch** [comment]
@stvogel sorry about that! I'll find some time soon to update the demo.
