### ISSUE TITLE
option for addWidgets to Unshift rather than push.

### ISSUE THREAD

**Issue by fsamir** [DataTorrent/malhar-angular-dashboard#141]
Hi there,

it would be nice to be able to call unshiftWidget, so widgets would be added to the beginning of the list, not the end like in addWidget.

Thanks

**Comment by wvary** [comment]
@fsamir I've created a PR to allow users to prependWidget to the dashboard.
You can do this in the dashboard or layout.
Here's the branch: https://github.com/DataTorrent/malhar-angular-dashboard/pull/187

**Comment by fsamir** [comment]
Thanks a lot. I will be testing it ASAP.
