### ISSUE TITLE
custom template example - question

### ISSUE THREAD

**Issue by technimadhu** [DataTorrent/malhar-angular-dashboard#143]
Hi,
i want to use custom template as documented.
<div dashboard="dashboardOptions" template-url="path/to/my-template.html"></div>

I am getting compile errors using the widget directive. Can someone provide a simple example, which simply adds the widgets in widget definitions.

I had a template file with only the following contents  and I get error about widget.
(Error: [ngRepeat:iexp] Expected expression in form of '_item_ in _collection_[ track by _id_]' but got '\"widget'.
http://errors.angularjs.org/1.3.0/ngRepeat/iexp?p0=%5C%22widget)

-----------my-template.html looks like below ---------------------
```html     
```<div>
         ```<div ui-sortable=\"sortableOptions\" ng-model=\"widgets\" class=\"dashboard-widget-area\">
            ```<div ng-repeat=\"widget in widgets\" ng-style=\"widget.containerStyle\" class=\"widget-container\" widget>
               ```<div class=\"widget panel panel-default\">
                 ```<div class=\"widget-header panel-heading\">
                 ```</div>
                  ```<div class=\"panel-body widget-content\" ng-style=\"widget.contentStyle\"></div>
             ```  </div>
           ``` </div>
        ``` </div>
     ``` </div>
'''

**Comment by robertmazzo** [comment]
my template looks similar. not sure what's wrong :

       <div>    
    
    <div ng-include="'app/shared/layout/inner-navbar.html'"></div>

    <div ui-sortable="sortableOptions" ng-model="widgets" class="dashboard-widget-area">
        <div ng-repeat="widget in widgets" ng-style="widget.containerStyle" class="widget-container" widget>
            <div class="widget panel panel-default">
                <div class="widget-header panel-heading">                   
                    <h3 class="panel-title">
                        <span class="widget-title" ng-dblclick="editTitle(widget)" ng-hide="widget.editingTitle">{{widget.title}}</span>
                        <form action="" class="widget-title" ng-show="widget.editingTitle" ng-submit="saveTitleEdit(widget)">
                            <input type="text" ng-model="widget.title" class="form-control">
                        </form>
                        
                        <span title="remove" ng-click="removeWidget(widget);" class="glyphicon glyphicon-remove" ng-if="!options.hideWidgetClose"></span>
                        <span title="config" ng-click="openWidgetSettings(widget);" class="glyphicon glyphicon-cog" ng-if="!options.hideWidgetSettings"></span>

                                                
                        <span title="{{widget.maximized ? 'restore' : 'maximize'}}" ng-show="widget.gadgetConfigured" ng-click="maxResizer($event)" class="glyphicon" ng-class="{'glyphicon-fullscreen': !widget.maximized, 'glyphicon-collapse-down': widget.maximized}" ></span>

                        
                        <span title="collapse" ng-show="widget.gadgetConfigured" ng-click="widget.contentStyle.display = (widget.contentStyle.display === 'none' ? 'block' : 'none')" class="glyphicon" ng-class="{'glyphicon-plus': widget.contentStyle.display === 'none', 'glyphicon-minus': widget.contentStyle.display !== 'none' }"></span>

                        
                        <span ng-show="widget.gadgetConfigured && !widget.maximized" title="refresh" ng-click="refreshGadget(widget);" class="glyphicon glyphicon-refresh" ></span>

                        
                    </h3>
                </div>                

          

                
            </div>
        </div>
    </div>

**Comment by technimadhu** [comment]
silly mistake. I removed the escape backslash before quotes and just used quotes and it works fine.
Thanks.
