### ISSUE TITLE
ModalInstance provider error after installing dashboard

### ISSUE THREAD

**Issue by deepthiravadi** [DataTorrent/malhar-angular-dashboard#147]
Here is my main controller
ilex_ctrls.controller('nocanswerRatesCtrl', function ($rootScope, $scope, $http, $location, widget) {
    getnoc_answer_ratesData($rootScope, $scope, $http, $location, widget);
});

function getnoc_answer_ratesData($rootScope, $scope, $http, $location, widget) {

```
$scope.myDashboardOptions = {
    widgetDefinitions: [
        {
            name: 'nocAnswerRates',
            template: '<div>hello {{widget.title}}</div>',
            settingsModalOptions: {
                templateUrl: '/template/pages/template_noc_answer_rates.html',
                controller: 'WidgetSettingsCtrl'
            }

            // defaultWidgets: myDefaultWidgets
        }
    ]


}
```

}

and this is my widget controller

ilex_ctrls.controller('WidgetSettingsCtrl', function ($rootScope, $scope, $http, $routeParams, $window, $interval) {
    $scope.header_height = 56 + 30;
    $rootScope.onResize = function () {
        $scope.window_height = $window.innerHeight;
    };
    $scope.onResize();
    angular.element($window).bind('resize', function () {
        $scope.onResize();
    });
    loadnoc_answer_rates($scope, $http);
    $interval(function () {
        loadnoc_answer_rates($scope, $http);
    }, 300000);
});

why is it throwing modalInstance  Provider error, I tried including in the service, but no luck,please help.Iam new to this.

**Comment by robertmazzo** [comment]
I'm thinking your `tempateUrl` should NOT have the initial back slash character `'\'` .
Maybe try without it - ex/ `templateUrl: 'template/pages/template_noc_answer_rates.html'`

**Comment by deepthiravadi** [comment]
Hi, How do I set this application,how  do I set my custom widget, I am  trying hard on this but cant set this up..please help!

**Comment by deepthiravadi** [comment]
Iam using latest ui bootstrap 0.13 version and I changed the url code,but still it throws modal instance error..

**Comment by robertmazzo** [comment]
I suggest that you download the zip file here https://github.com/DataTorrent/malhar-angular-dashboard , and try to run their sample app first. Then you can dig in further to see how things work.

**Comment by deepthiravadi** [comment]
Yeah I am doing that  now. Could not figure out how to resolve that bug though. Thanks

**Comment by robertmazzo** [comment]
does your app.js contain the 'ui.bootstrap' dependency ? And what about your index.html.

**Comment by deepthiravadi** [comment]
Yes, its already there  'ui.bootstrap', and index.php has

	<script src="/js/angular/ui-bootstrap-tpls-0.13.4.min.js"></script>

**Comment by deepthiravadi** [comment]
I included these in app.js
 'ui.dashboard',
    'ui.sortable',
    'ui.widgets' , not sure why its not working.How do I set a custom widget in the controller?

**Comment by deepthiravadi** [comment]
I am getting this error
_ is not defined
    at new controller (angular-ui-dashboard.js:54)
How can I resolve this bug..
what are the files  to be included in app.js for ui.models?
Can someone help..

.Iam working on the demo  from webapp.

**Comment by robertmazzo** [comment]
I'll try and have a look soon...I understand because I struggled for a while myself, and still do at times.

**Comment by tskapo** [comment]
Hi Deethiravadi, 
To fix the problem with missing _, I guess, you need to include Lodash. This library is used in sources

**Comment by deepthiravadi** [comment]
I included loadash and loadash min .js files, but it still throws the error..

**Comment by rachellcarbone** [comment]
Is that Lodash or Underscore?

**Comment by rachellcarbone** [comment]
You're right that is Lodash. But the documentation said Underscore :(

**Comment by wvary** [comment]
@deepthiravadi I'm sorry for the late response, but have you resolved the modalInstance error issue?

**Comment by wvary** [comment]
@deepthiravadi Issue is considered resolved unless we're informed otherwise.
