### ISSUE TITLE
Demo application

### ISSUE THREAD

**Issue by bhanu3loq** [DataTorrent/malhar-angular-dashboard#150]
Hi Team,

I am not sure if this is the right place to my question or not. I am trying to run demo of Malhar-angluar-dashboard. I followed all the instructions which are listed in the readme.

I tried running grunt demo.

loq-1@3loq-1:~/bower_components/malhar-angular-dashboard$ grunt demo
Running "connect:livereload" (connect) task
Started connect web server on http://10.10.1.140:9000

Running "watch" task
Waiting...
I got the above output.

But when i tried of accessing the url from the web. I can see only the below two files.
    malhar-angular-dashboard.css
    malhar-angular-dashboard.js
It is not showing me anything else. Please suggest me the instructions to run grunt demo.

Thanks in advance. Sorry if this is the wrong place to post my question. It would be really helpful if you can improve readme.md 

Thanks,
Bhanu.B

**Comment by sashadt** [comment]
Please following commands to run the demo.

```
bower install
gulp build:demo
gulp serve
```
