### ISSUE TITLE
malhar-angular-dashboard does not support latest version of angular-ui-bootstrap

### ISSUE THREAD

**Issue by Exotelis** [DataTorrent/malhar-angular-dashboard#151]
$modal is deprecated since angular-bootstrap#0.14.0
I recommend to use $uibModal instead.

![error](https://cloud.githubusercontent.com/assets/7863239/11651425/e7dd8720-9d90-11e5-8503-7b10c957396a.jpg)

Edit*:
See https://github.com/DataTorrent/malhar-angular-dashboard/pull/161
All checks have passed. A merge would be nice :)

**Comment by ablock** [comment]
This seems resolved by:

https://github.com/DataTorrent/malhar-angular-dashboard/pull/164

Can this issue be closed?

**Comment by Exotelis** [comment]
Yes it can.
Thanks for merging my pull request.
