### ISSUE TITLE
widgetDefs.map is not a function

### ISSUE THREAD

**Issue by pitong** [DataTorrent/malhar-angular-dashboard#155]
.factory('widgetRestService',['$http','UrlService','$log','$q',
    function($http,UrlService,$log,$q){

```
  var serviceInstance = {
    //widgets:[]
  };

  serviceInstance.getInfo = function(){
    var request = $http({method: 'GET', url: '/rest/widgets/getListInfoDashboards'})
      .then(function(success){
        serviceInstance.widgets = success.data;
        $log.debug('serviceInstance.widgets SUCCESS',serviceInstance.widgets);
      },function(error){
        $log.debug('Error ', error);
        $log.debug('serviceInstance.widgets ERROR',serviceInstance.widgets);
      });
    return request;
  };

  serviceInstance.getAllWidgets = function () {
    if (serviceInstance.widgets) {
      return serviceInstance.widgets;
    } else {
      return [];
    }
  };

  return serviceInstance;
```

  }]);
   // widgets returns an array like :
         [
           {
              name:'widgetList',
              title:'title1'
           },
          {
              name:'widgetPie',
              title:'title2'
           },
           {
              name:'widgetTable',
              title:'title1'
           }
         ]

With this service I will shape my widgetDefinitions in the widgetDefinitions service

.factory('widgetDefinitions',['widgetRestService','$log','$q','$http',function(widgetRestService,$log,$q,$http) {

```
 var widgetDefinitions = [];
return widgetRestService.getInfo().then(function (data) {

  var widgets = widgetRestService.getAllWidgets();
  $log.debug('widgetsDefs ', widgets);
  for (var i = 0; i < widgets.length; i++) {
    widgetDefinitions.push(widgets[i]);
  }
  $log.debug('widgetDefinitions ', widgetDefinitions);
  return widgetDefinitions;
});
```

  // console: widgetDefinitions: [Object,Object,Object]
}

So I manage to return an array with the required key: name and still doesn`t work
RESTUL : TypeError: widgetDefs.map is not a function

**Comment by robertmazzo** [comment]
Where exactly is it throwing the exception ? Is it in the `dashboard` directive code, in the loadWidgets function ?

**Comment by pitong** [comment]
at Array.WidgetDefCollection (http://localhost:9000/bower_components/malhar-angular-dashboard/dist/malhar-angular-dashboard.js:949:31)
    at link (http://localhost:9000/bower_components/malhar-angular-dashboard/dist/malhar-angular-dashboard.js:80:28)
    at invokeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8194:9)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7706:11)
    at delayedNodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7955:11)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7062:13)
    at publicLinkFn (http://localhost:9000/bower_components/angular/angular.js:6941:30)
    at boundTranscludeFn (http://localhost:9000/bower_components/angular/angular.js:7080:16)
    at controllersBoundTransclude (http://localhost:9000/bower_components/angular/angular.js:7733:18)
    at ngRepeatAction (http://localhost:9000/bower_components/angular/angular.js:24487:15) <div ng-repeat="layout in layouts | filter:isActive" dashboard="layout.dashboard" template-url="components/directives/dashboard/dashboard.html" class="ng-scope">

**Comment by robertmazzo** [comment]
I don't see  line 949 in my older version (i.e. `widgetDefs = widgetDefs.map(convertToDefinition);`)

In my version of the factory code, they build the `map` array and assign it to this.map :

        angular.module('ui.dashboard')
.factory('WidgetDefCollection', function () {
function WidgetDefCollection(widgetDefs) { 

  // build (name -> widget definition) map for widget lookup by name
  var map = {};
  _.each(widgetDefs, function (widgetDef) {                              
		  map[widgetDef.name] = widgetDef;              
  });
  this.map = map;
}

It looks as if there's supposed to be a `map` method on `widgetDefs` but it doesn't exist. Am I missing something ? I know I have an older version...

Bob
WidgetDefCollection.prototype = Object.create(Array.prototype);

WidgetDefCollection.prototype.getByName = function (name) {
  return this.map[name];
};

return WidgetDefCollection;
     });

**Comment by pitong** [comment]
I have it...

WidgetDefCollection.prototype = Object.create(Array.prototype);

    WidgetDefCollection.prototype.getByName = function (name) {
      return this.map[name];
    };

    WidgetDefCollection.prototype.add = function(def) {
      def = convertToDefinition(def);
      this.push(def);
      this.map[def.name] = def;
    }

    return WidgetDefCollection;
  });

**Comment by wvary** [comment]
@pitong Make sure the dashboard options contains a property named widgetDefinitions and it's an array, even if it's empty.  Also make sure the the browser version you're using supports the map function for arrays.  This map function for array became the ECMA-262 standard in the 5th edition so your browser version might not have it supported.
