### ISSUE TITLE
Simple demo URL of source code is not working...

### ISSUE THREAD

**Issue by NoNameCode** [DataTorrent/malhar-angular-dashboard#157]
Hello!
I wanted to review source code of Simple demo

"<i>Simple demo (minimum dependencies) [source code]</i>"

but it shows 404 error. Could you please update/upload this section and put correct link?

Thank you!

**Comment by ChrisWiGit** [comment]
Try the old version:
https://github.com/DataTorrent/malhar-angular-dashboard/tree/v0.8.2/demo
No idea if its still works.

**Comment by wvary** [comment]
Issue #144 already reported this problem.
I've created PR for it.
