### ISSUE TITLE
How do I recompile the layout-dashboard directive ? 

### ISSUE THREAD

**Issue by pitong** [DataTorrent/malhar-angular-dashboard#158]
StackOverflow thread: http://stackoverflow.com/questions/34631966/how-to-reload-recompile-refresh-directive-in-angularjs

**Comment by awashbrook** [comment]
you may find #136 helps your case, although I personally tried out the hack suggested by @andyperlitch  and couldn't get it to work!

**Comment by pitong** [comment]
yes, I tried that myself and doesn`t work...

**Comment by pitong** [comment]
We need a way to pass controller scope variables to the directive variables, something like this: http://stackoverflow.com/questions/13318726/easiest-way-to-pass-an-angularjs-scope-variable-from-directive-to-controller >> http://jsfiddle.net/maxisam/QrCXh/

**Comment by robertmazzo** [comment]
I've struggled with this for a while regarding the use of the `Kendo UI` library, and found a hack to force a widget recompile. My original post was #142 .
It started when I discovered the `scope.compileTemplate()` function call in the `widget` directive code.

In my case, I searched for the Kendo grid class `.k-grid`, then found this method on the angular scope object:
          $angular_scope.compileTemplate();

So in my refresh code, I first looked for any Kendo grid in the DOM:

           var grids = $(angular.element(document.getElementById('dash'))).find('.k-grid');

I then used `_.each()` to iterate the DOM elements:
        
              _.each(grids, function (elem) {
                        var grid = $(elem).parent().find('.k-grid').data('kendoGrid');   // this 
                         // add'l code omitted...
                });

It's not very elegant, but it does recompile my HTML code when I'm dynamically swapping out the `templateURL` property of the widgets definition.

good luck,
Bob

**Comment by pitong** [comment]
That`s interesting, thanks a lot, I also find some sort of usage to my problem. In the first $scope.layoutOptions.widgetDefinitions = define_all_widget_you_want; and then after changes you can redefine $scope.layoutOptions.widgetDefinitions = less_widget_list; I will have same effect (The map has all the widgets but we are displaying less widgets :D ).

**Comment by robertmazzo** [comment]
My scenario does not use the layout-dashboard, but I did find the recompile hack useful. 
Are you using the `WidgetDataModel` to configure your widget data ?

**Comment by pitong** [comment]
No, I`m not using any WidgetDataModel

**Comment by wvary** [comment]
@pitong accepted the answer on stackoverflow.
Assuming this issue has been resolved.
