### ISSUE TITLE
source code Line 27 : attr.templateUrl -> attr.templateurl 

### ISSUE THREAD

**Issue by JINGTINGWU** [DataTorrent/malhar-angular-dashboard#162]
HTML
`<div dashboard="myDashboardOptions" templateUrl="......"></div>`

Source Code **Line 27**：
`
      return attr.templateUrl ? attr.templateUrl : 'components/directives/dashboard/dashboard.html';
`
 It should be **attr.templateurl**

**Comment by wvary** [comment]
@JINGTINGWU This line is correct:
return attr.templateUrl ? attr.templateUrl : 'components/directives/dashboard/dashboard.html';

In the HTML code, you should specify:
<div dashboard="myDashboardOptions" template-url="......"></div>

template-url in HTML maps to templateUrl in Javascript.

Just make sure the html template path is valid.

Thanks.
