### ISSUE TITLE
Any plans to upgrade to Angular2?

### ISSUE THREAD

**Issue by ajayambre** [DataTorrent/malhar-angular-dashboard#169]
We are using malhar-angular-dashboard in our app written in Angular 1.x.
We are planning to upgrade our application to Angular 2 and would like to know the plans for malhar-angular-dashboard.

**Comment by jennyphan** [comment]
We are also looking to create a new application using Angular 2 and I have used this dashboard and I love it.  I am also wondering if there is a plan to upgrade to Angular2?

**Comment by wvary** [comment]
@ajayambre @jennyphan We will eventually update this library to use Angular2, but there is no immediate plan to do so.
