### ISSUE TITLE
changing dashboard template doesn't work

### ISSUE THREAD

**Issue by ashishtilara** [DataTorrent/malhar-angular-dashboard#171]
I tried to set the `templateUrl` attribute as following

```
<div dashboard="ctrl.dashboardOptions" class="dashboard-container" templateUrl="partials/lists/dashboard.html"></div>
```

but that doesn't seem to work, I would like to change the template for widgets and dashboard itself, is it possible to add example for showing this.

cheers

**Comment by awashbrook** [comment]
@ashishtilara this functionality was contributed by me a couple of years ago and our webapp is using it in in production still, see #35. have a look at the jasmine tests for a case using  https://github.com/DataTorrent/malhar-angular-dashboard/blob/master/src/components/directives/dashboard/altDashboard.html

**Comment by wvary** [comment]
@ashishtilara As mentioned by @awashbrook, this feature is supported.  Make sure you type template-url not templateUrl.

Change:
<div dashboard="ctrl.dashboardOptions" class="dashboard-container" **templateUrl**="partials/lists/dashboard.html"></div>

to:
<div dashboard="ctrl.dashboardOptions" class="dashboard-container" **template-url**="partials/lists/dashboard.html"></div>

Let us know if you run into any issue.
