### ISSUE TITLE
'resolve' property for settingsModalOptions is lost

### ISSUE THREAD

**Issue by megavoltua** [DataTorrent/malhar-angular-dashboard#181]
If you set any data in settingsModalOptions.resolve, it is destroyed by the code in `malhar-angular-dashboard.js`, function `scope.openWidgetSettings`:

``` javascript
options.resolve = {
    widget: function () {
        return widget;
    }
};
```

Suggested to replace with smth like this:

``` javascript
options.resolve = _.extend({
    widget: function () {
        return widget;
    }
}, widget.settingsModalOptions.resolve);
```

**Comment by wvary** [comment]
Hi @megavoltua,

Feel free to create a PR with the features you would like to be in this project.  That way, everyone here will have a chance to review and we'll merge the code if the features may be useful to someone else.

Regards,

Willet
