### ISSUE TITLE
Active overflow when resizing widget

### ISSUE THREAD

**Issue by galiolas** [DataTorrent/malhar-angular-dashboard#192]
Hello, how could i  activate overflow on a table inside a widget? i'd like to resize the table while i'm resizing the widget, because the overflow of my table don't appear

Thank

**Comment by wvary** [comment]
Hi @galiolas,

Not sure what your big picture requirement is, but I'll try to answer with some assumptions.
If you are trying to resize the a table inside the widget, you can do that by setting the width of the table to 100%.  You can also set the min-width and max-width of the table as well.

As for overflow, you can place that table inside a div and set the overflow to auto on that div.
Take a look at PR 182.  I've added a table as another use case and the table resizes as the widget is resized.  I just didn't apply the overflow on the div, but that is quite simple to do.

Let me know if you need further assistance.

Regards,

Willet
