### ISSUE TITLE
Any ideas on responsiveness?

### ISSUE THREAD

**Issue by dk253** [DataTorrent/malhar-angular-dashboard#193]
Howdy!  Has anyone had any luck making the panels wrap responsively when moving to a mobile?  If I set the css min-width: 320px; the panels overlap on each other.  Any luck with a css that does this a little better?  Thanks!

**Comment by wvary** [comment]
Hi @dk253,

Checkout PR 182.  I've added the min-width feature in this PR to support such a use case.  You should see the widgets wrap to the next row when resizing the browser.

Regards,

Willet
