### ISSUE TITLE
Not able to install with the given instructions.

### ISSUE THREAD

**Issue by rkhapre** [DataTorrent/malhar-angular-dashboard#199]
Not able to install with the given instructions.

I see only DashboardBeta, Applications and Random Data Menu.

Do we have any wiki? or detailed documentation for this

**Comment by wvary** [comment]
Hi @rkhapre,

Not sure which steps you follow, but the following worked for me:

1. git clone https://github.com/DataTorrent/malhar-angular-dashboard.git
2. cd malhar-angular-dashboard
3. bower install
4. npm install
5. gulp bower:demo (optional)
6. gulp serve

![image](https://user-images.githubusercontent.com/3396089/30493159-f325cd8a-99f7-11e7-847e-7080c07eda37.png)
