### ISSUE TITLE
hi i want to work on this and i need permission to download

### ISSUE THREAD

**Issue by kvsskk** [DataTorrent/malhar-angular-dashboard#200]
hi, im new to the designing of UI and I really like working with the malhar angular webapp dashboard, can you give me permission to work on this

**Comment by wvary** [comment]
Hi @kvsskk, you can fork this repository and create pull requests with bug fixes and feature enhancements.  We'll merge them as we review the PRs.  This is an open source library so everyone is welcome to participate.

**Comment by kvsskk** [comment]
Thank you

On 28 Aug 2017 21:17, "Willet Vary" <notifications@github.com> wrote:

Hi @kvsskk <https://github.com/kvsskk>, you can fork this repository and
create pull requests with bug fixes and feature enhancements. We'll merge
them as we review the PRs. This is an open source library so everyone is
welcome to participate.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DataTorrent/malhar-angular-dashboard/issues/200#issuecomment-325392283>,
or mute the thread
