### ISSUE TITLE
Migrate from ngmin to ng-annotate

### ISSUE THREAD

**Issue by awashbrook** [DataTorrent/malhar-angular-dashboard#69]
Following original discussion in #37 [ngmin](https://github.com/btford/ngmin) is now officially deprecated in favor of [ng-annoate](https://github.com/olov/ng-annotate); even NPM is giving warnings!
```
npm WARN deprecated ngmin@0.4.1: use ng-annotate instead
```
Presumably you would also embrace [grunt](https://www.npmjs.org/package/grunt-ng-annotate) tool also?

**Comment by andyperlitch** [comment]
this is fixed on release-2.0.0 branch
