### ISSUE TITLE
About different widgetDefinitions for each layout (tabs)

### ISSUE THREAD

**Issue by gabrielacosta** [DataTorrent/malhar-angular-dashboard#83]
Good Afternoon, 

I was reviewing the current documentation and I notice that the layouts have the restriction of set a define default widgets for al the layouts.

https://github.com/DataTorrent/malhar-angular-dashboard#widget-definition-objects
Dashboard Layouts
One common requirement for user-customizable dashboards is the ability to have multiple layouts consisting of the same set of widget definitions. 

Currently, I need to have exactly the opposite and I want to specific set of default widgets for each layout.
I know that the layouts properties are defined in 

.controller('LayoutsDemoExplicitSaveCtrl', function($scope, widgetDefinitions, defaultWidgets, LayoutStorage, $interval) {
		$scope.layoutOptions = {
		storageId: 'demo-layouts-explicit-save',
		storage: localStorage,
		storageHash: 'fs4df4d51',
		widgetDefinitions: widgetDefinitions,
		defaultWidgets: defaultWidgets,
		explicitSave: true,
		defaultLayouts: [
		{ title: 'Layout 1', active: true , defaultWidgets: defaultWidgets1 },
		{ title: 'Layout 2', active: false, defaultWidgets: defaultWidgets2 },
		{ title: 'Layout 3', active: false, defaultWidgets: defaultWidgets3 }
		]
	};

It is possible to pass the widgetDefinitions for each layout as well as the defaultwidgets?

It is possible to achieve this kind of functionality in any customized way?

Thank you for the hard work.

Regards,

Gabriel Acosta

**Comment by andyperlitch** [comment]
implemented on release-1.0.0 branch
