### ISSUE TITLE
Feature request: minimize button

### ISSUE THREAD

**Issue by adrianandreias** [DataTorrent/malhar-angular-dashboard#99]
Would be useful to have a minimize button implemented.

**Comment by robertmazzo** [comment]
At some point soon, I'd like to take a crack at a minimize/maximize button in the widget headers. I have an Angular directive already doing this on the Bootstrap "Metro" theme that I downloaded last year. I'd like to try and apply that to this Dashboard, and will notify the community upon success.

**Comment by awashbrook** [comment]
We are very interested in this for our dashboard which also approach internal 1.0.0 milestone :)

**Comment by andyperlitch** [comment]
done on release-1.0.0 branch
